In [2]:
import numpy as np
import matplotlib.pyplot as plt

A = np.array([[2,3,4],
            [10,20,30]])

B = np.array([[2,3,4],
            [10,20,30]], dtype = np.float32)            

print("Matrix A = \n", A)
print("Matrix Of A = ", A.shape)
print("Dtype of A = ", A.dtype)

print("Matrix B = \n", B)
print("Matrix Of B = ", B.shape)
print("Dtype of B = ", B.dtype)

Matrix A = 
 [[ 2  3  4]
 [10 20 30]]
Matrix Of A =  (2, 3)
Dtype of A =  int32
Matrix B = 
 [[ 2.  3.  4.]
 [10. 20. 30.]]
Matrix Of B =  (2, 3)
Dtype of B =  float32


In [3]:
## Diagonal
a = np.array([1, 2, 3, 4])
D_1 = np.diag(a)
print("D_1 = \n", D_1)

b = np.random.randint(1,10,5)
D_2 = np.diag(b) 
print("D_2 = \n", D_2)

D_1 = 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
D_2 = 
 [[9 0 0 0 0]
 [0 5 0 0 0]
 [0 0 8 0 0]
 [0 0 0 3 0]
 [0 0 0 0 9]]


In [4]:
## 단위 행렬, Identity
I_3 = np.eye(3)
print("3 x 3 Identity = \n", I_3)

I_5 = np.eye(5)
print("5 x 5 Identity = \n", I_5)


3 x 3 Identity = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
5 x 5 Identity = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# 전치 행렬, Matrix Transpose
A = np.array([[1,2,3,4],
            [5,6,7,8]], dtype = np.int64)
print("A = \n", A)
print("transpose A =  \n",A.T)  

A = 
 [[1 2 3 4]
 [5 6 7 8]]
transpose A =  
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [7]:
## matrix multiplication
A = np.array([[1, 2]
            , [3, 4]])
B = np.array([[1, 1]
            , [1, 2]])

print("AB = \n", AB)
print("A x B = \n", np.matmul(A, B))

NameError: name 'AB' is not defined